/**
 * Analysis Types - Tiered Analysis Engine (Frontend)
 * 
 * This module defines the interfaces for the polymorphic API response
 * based on the user's subscription tier (FREE | PRO).
 * Mirrors the backend types for type-safe API consumption.
 */

/**
 * StandardSnapshot - Base financial data available to all users (FREE + PRO)
 * 
 * Contains the fundamental financial health indicators:
 * - Total Assets
 * - Total Liabilities
 * - Net Worth
 */
export interface StandardSnapshot {
  /** Total value of all assets (excluding cash) */
  totalAssets: number;
  /** Total value of all liabilities */
  totalLiabilities: number;
  /** Net Worth = Total Assets - Total Liabilities + Cash */
  netWorth: number;
  /** Total cash/savings balance */
  totalCash: number;
  /** Currency information */
  currency: {
    symbol: string;
    name: string;
  };
  /** Snapshot timestamp */
  asOfDate: string;
}

/**
 * DebtComposition - Good vs Bad debt classification
 * 
 * Good Debt: Debt tied to income-producing assets (assetId is not null)
 * Bad Debt: Debt not tied to any asset (assetId is null)
 */
export interface DebtComposition {
  /** Total value of liabilities linked to assets (leveraged debt for income-producing assets) */
  goodDebt: number;
  /** Total value of liabilities NOT linked to any asset (consumer debt, etc.) */
  badDebt: number;
  /** Good debt as percentage of total debt */
  goodDebtRatio: number;
  /** Bad debt as percentage of total debt */
  badDebtRatio: number;
}

/**
 * AssetEfficiency - Classification of assets by productivity
 * 
 * Productive Assets: Assets with at least one linked income line
 * Stagnant Assets: Assets with no linked income lines
 */
export interface AssetEfficiency {
  /** Total value of assets that generate income (incomeLines.length > 0) */
  productiveAssets: number;
  /** Total value of assets that do NOT generate income (incomeLines.length === 0) */
  stagnantAssets: number;
  /** Number of productive assets */
  productiveAssetCount: number;
  /** Number of stagnant assets */
  stagnantAssetCount: number;
  /** Productive assets as percentage of total asset value */
  productivityRatio: number;
}

/**
 * Individual asset breakdown with linked income and liability details
 */
export interface AssetBreakdownItem {
  /** Asset ID */
  assetId: number;
  /** Asset name */
  assetName: string;
  /** Asset value */
  assetValue: number;
  /** Whether this asset is productive (has income) */
  isProductive: boolean;
  /** Total income generated by this asset */
  linkedIncomeTotal: number;
  /** Number of income lines linked */
  linkedIncomeCount: number;
  /** Total liabilities linked to this asset */
  linkedLiabilityTotal: number;
  /** Number of liabilities linked */
  linkedLiabilityCount: number;
  /**
   * True Yield = (Linked Income - Linked Liability Costs) / Asset Value * 100
   * Represents the actual return after accounting for associated debt
   */
  trueYield: number;
}

/**
 * AdvancedMetrics - Pro-tier exclusive financial analytics
 * 
 * Contains deep financial insights only available to PRO subscribers:
 * - Debt composition (Good vs Bad)
 * - Asset efficiency scores
 * - Advanced ratios and projections
 */
export interface AdvancedMetrics {
  /** Good/Bad debt split analysis */
  debtComposition: DebtComposition;
  /** Productive/Stagnant asset analysis */
  assetEfficiency: AssetEfficiency;
  /** Advanced financial ratios */
  metrics: {
    /**
     * Debt Service Ratio = Total Monthly Liabilities / Total Monthly Income
     * Lower is better (indicates less income goes to debt service)
     */
    debtServiceRatio: number;
    /**
     * Passive Runway = Cash / (Monthly Expenses - Monthly Passive Income)
     * Number of months expenses can be covered if earned income stops
     * Returns Infinity if passive income >= expenses (financially free)
     */
    passiveRunway: number;
    /**
     * Estimated date when passive income will cover all expenses
     * Based on current growth trajectory
     * Returns null if cannot be calculated or already achieved
     */
    passiveIncomeCrossoverDate: string | null;
  };
  /** Detailed breakdown of linked items per asset */
  assetBreakdown: AssetBreakdownItem[];
}

/**
 * AnalysisResponse - Polymorphic API response based on subscription tier
 * 
 * The main response type for GET /api/analysis/snapshot endpoint.
 * - FREE users: standard data + advanced = null
 * - PRO users: standard data + advanced metrics populated
 */
export interface AnalysisResponse {
  /** Base financial snapshot - available to all tiers */
  standard: StandardSnapshot;
  /** Advanced metrics - null for FREE tier, populated for PRO tier */
  advanced: AdvancedMetrics | null;
  /** Indicates whether the user has PRO subscription */
  isPro: boolean;
  /** User's subscription tier */
  tier: 'FREE' | 'PRO';
}

/**
 * Subscription tier type
 */
export type SubscriptionTier = 'FREE' | 'PRO';
